#!/usr/bin/env bash
up() {

  echo "Starting Portainer..."
  docker volume create portainer_data
  docker run -d -p 8000:8000 -p 9443:9443 --name crea-sc-manager \
  --restart=always \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v portainer_data:/data portainer/portainer-ce:latest &

}

down() {
  docker stop crea-sc-manager
  docker rm crea-sc-manager
}

case $1 in
  up)
    up
    ;;
  down)
    down
    ;;
  *)
    echo "Usage: $0 {up|down}"
    ;;
esac


